### ISSUE TITLE
Individual and species count discrepancy

### ISSUE THREAD

**Issue by jgradym** [qdread/forestlight#1]
In lines 1100-1200 of clean_plotting_code.R, I tried to merge individual count data from prod_ratio_light to richness_ratio_light. Upon doing so, I noticed the counts of species and of individuals were inconsistent - in some cases there were more species than individuals.

**Comment by qdread** [comment]
I added code to richness_ratio_trend.R in commit 4c1433d. Additional columns added to richness_wide and richness_wide light to give the minimum n individuals between the two FGs in the ratio pair. All the n individuals are >= the richness, so there is no discrepancy. I didn't parse the code you wrote in clean plotting code but hopefully you can use what I wrote. Please confirm it's OK and close issue if so!

**Comment by jgradym** [comment]
Looks good
